APP_URL = 'https://raw.githubusercontent.com/burov-kirill/EscrowMatching/master/dist/EscrowMatching.exe'
ZIP_URL = 'https://raw.githubusercontent.com/burov-kirill/EscrowMatching/master/dist/EscrowMatching.exe'
APP_NAME = 'EscrowMatching.exe'
VERSION = '1.0.1'
VERSION_URL = 'https://raw.githubusercontent.com/burov-kirill/EscrowMatching/main/__VERSION__'
UPDATE_NAME = 'update.exe'
UPDATE_FOLDER = 'config'
UPDATE_URL = 'https://raw.githubusercontent.com/burov-kirill/Updater/master/dist/update.exe'
